/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesNewRouteImport } from './routes/sales/new'
import { Route as IntakeNewRouteImport } from './routes/intake/new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeNewRoute = IntakeNewRouteImport.update({
  id: '/intake/new',
  path: '/intake/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/ledger'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/ledger'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/ledger'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  LedgerRoute: typeof LedgerRoute
  SetupRoute: typeof SetupRoute
  IntakeNewRoute: typeof IntakeNewRoute
  SalesNewRoute: typeof SalesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/new': {
      id: '/intake/new'
      path: '/intake/new'
      fullPath: '/intake/new'
      preLoaderRoute: typeof IntakeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof ContactsRoute
    }
  }
}

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRouteWithChildren,
  LedgerRoute: LedgerRoute,
  SetupRoute: SetupRoute,
  IntakeNewRoute: IntakeNewRoute,
  SalesNewRoute: SalesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
