/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as SalesNewRouteImport } from './routes/sales/new'
import { Route as IntakeNewRouteImport } from './routes/intake/new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRoute,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const IntakeNewRoute = IntakeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntakeRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/intake': typeof IntakeRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
  '/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/intake': typeof IntakeRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/sales': typeof SalesRouteWithChildren
  '/setup': typeof SetupRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/intake/new': typeof IntakeNewRoute
  '/sales/new': typeof SalesNewRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/intake'
    | '/ledger'
    | '/sales'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intake'
    | '/ledger'
    | '/sales'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/intake'
    | '/ledger'
    | '/sales'
    | '/setup'
    | '/contacts/$contactId'
    | '/intake/new'
    | '/sales/new'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  IntakeRoute: typeof IntakeRouteWithChildren
  LedgerRoute: typeof LedgerRoute
  SalesRoute: typeof SalesRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/intake/new': {
      id: '/intake/new'
      path: '/new'
      fullPath: '/intake/new'
      preLoaderRoute: typeof IntakeNewRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof ContactsRoute
    }
  }
}

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface IntakeRouteChildren {
  IntakeNewRoute: typeof IntakeNewRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeNewRoute: IntakeNewRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

interface SalesRouteChildren {
  SalesNewRoute: typeof SalesNewRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesNewRoute: SalesNewRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRouteWithChildren,
  IntakeRoute: IntakeRouteWithChildren,
  LedgerRoute: LedgerRoute,
  SalesRoute: SalesRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
